sudo: false
language: ruby
rvm:
  - 2.2.4
addons:
  apt:
    packages:
     - libdb-dev
     - libxml2-dev
     - libxslt1-dev
     - libgdbm-dev
before_install:
  - gem install bundler -v 1.12.5
  # Thanks to SO: http://stackoverflow.com/a/32358866
  # Install modules into ~/perl5 using system perl
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - export PATH=$PATH:~/perl5/bin/
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm JSON
  - cpanm --notest https://github.com/brucemiller/LaTeXML.git
  - cpanm https://github.com/dginev/LaTeXML-Plugin-latexmls.git
